### ISSUE TITLE
Datepicker + style form

### ISSUE THREAD

**Issue by MWCorentin** [symfony-billetterie/symfony-billetterie#108]
- [x] Datepicker Bootstrap 3
- [x] Couleur input de tous les forms

**Comment by GregRdt** [comment]
<div class="container">
    <div class="col-sm-6" style="height:130px;">
        <div class="form-group">
            <div class='input-group date' id='datetimepicker9'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar">
                    </span>
                </span>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker9').datetimepicker({
                viewMode: 'years'
            });
        });
    </script>
</div>
