### ISSUE TITLE
Configuration - Doctrine fixtures

### ISSUE THREAD

**Issue by GregRdt** [symfony-billetterie/symfony-billetterie#59]
- [x] Ajouter un nouveau bundle pour les fixtures (doctrine-fixtures-bundle)

**Comment by MWCorentin** [comment]
@GregRdt les fixtures sont faites depuis deux semaines, j'ai oublié de changé le label

**Comment by GregRdt** [comment]
@MWCorentin Comme tu as participé à l'issue je te l'assigne aussi.
