### ISSUE TITLE
Templates des pages d'erreur

### ISSUE THREAD

**Issue by GregRdt** [symfony-billetterie/symfony-billetterie#72]
Faire les templates des pages suivantes :

- [x] Page erreur 403, Vous n'avez pas la permission d'accéder à cette page.
- [x] Page erreur 404, La page demandée n'existe pas.
- [x] Page erreur 500, Une erreur technique est survenue.

Le code de l'erreur et le message doivent être présents sur chaque page.

**Comment by MWCorentin** [comment]
#71 @GregRdt Associé à l'autre aussi je fais du deux en un

**Comment by GregRdt** [comment]
- [ ] Changer "Erreur 404 Not Found" en "Erreur 404"
- [ ] Changer "Page non trouvé" en "Page non trouvée"
- [ ] Changer "Erreur 403 Forbbiden" en "Erreur 403"
- [ ] Changer "Vos droits d'accès ne vous permettent pas d'accèder à cette page" en "Vos droits d'accès ne vous permettent pas d'accéder à cette page"
