### ISSUE TITLE
Mettre en place Gedmo

### ISSUE THREAD

**Issue by GregRdt** [symfony-billetterie/symfony-billetterie#76]
- [x] Installer http://symfony.com/doc/current/doctrine/common_extensions.html pour pouvoir utiliser des slugs dans l'application

**Comment by MWCorentin** [comment]
@GregRdt C'était déjà fais quand j'ai mis en place le TimeStampTrait pour les logs
#49 
https://github.com/symfony-billetterie/symfony-billetterie/blob/master/src/AppBundle/Entity/Traits/TimeStampTrait.php
